# SPDX-FileCopyrightText: 2023 MASH project contributors
# SPDX-FileCopyrightText: 2023-2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 IUCCA
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "lookup('ansible.builtin.varnames', ('^' + item.old + '$'), wantlist=True) | length > 0"
  with_items:
    - { "old": "immich_machine_learning_container_tmp_tmpfs_enabled", "new": "immich_machine_learning_container_tmpfs_tmp_enabled" }
    - { "old": "immich_machine_learning_container_tmp_tmpfs_size_mb", "new": "immich_machine_learning_container_tmpfs_tmp_size" }

- name: Fail if required Immich settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item.name }}`).
  when: "item.when and lookup('vars', item.name, default='') | string | length == 0"
  with_items:
    - name: immich_uid
      when: true
    - name: immich_gid
      when: true
    - name: immich_server_hostname
      when: "{{ immich_server_enabled }}"
    - name: immich_server_path_prefix
      when: "{{ immich_server_enabled }}"
    - name: immich_server_container_network
      when: "{{ immich_server_enabled }}"
    - name: immich_machine_learning_container_network
      when: "{{ immich_machine_learning_enabled }}"

- name: Validate Immich server-related configuration when Immich server enabled
  when: immich_server_enabled | bool
  block:
    - name: Fail if immich_server_transcoding_hardware_acceleration is invalid
      ansible.builtin.fail:
        msg: >-
          immich_server_transcoding_hardware_acceleration (`{{ immich_server_transcoding_hardware_acceleration }}`) must be one of: cpu, nvenc, quicksync, rkmpp, vaapi, vaapi-wsl.
      when: immich_server_transcoding_hardware_acceleration not in ['cpu', 'nvenc', 'quicksync', 'rkmpp', 'vaapi', 'vaapi-wsl']

    - name: Validate Immich Traefik labels-related configuration when Traefik labels enabled
      when: immich_server_container_labels_traefik_enabled | bool
      block:
        - name: Fail if required Immich Traefik settings not defined
          ansible.builtin.fail:
            msg: >-
              You need to define a required configuration setting (`{{ item }}`).
          when: "lookup('vars', item, default='') | string | length == 0"
          with_items:
            - immich_server_container_labels_traefik_hostname
            - immich_server_container_labels_traefik_path_prefix

        - name: Fail if immich_server_container_labels_traefik_path_prefix is not `/`
          ansible.builtin.fail:
            msg: >-
              immich_server_container_labels_traefik_path_prefix (`{{ immich_server_container_labels_traefik_path_prefix }}`) must be `/` due to Immich limitations (see https://github.com/immich-app/immich/issues/14530)
          when: "immich_server_container_labels_traefik_path_prefix != '/'"

- name: Validate Immich Machine Learning-related configuration when Immich Machine Learning enabled
  when: immich_machine_learning_enabled | bool
  block:
    - name: Fail if immich_machine_learning_hardware_acceleration is invalid
      ansible.builtin.fail:
        msg: >-
          immich_machine_learning_hardware_acceleration (`{{ immich_machine_learning_hardware_acceleration }}`) must be one of: armnn, cuda, cpu, openvino, openvino-wsl, rknn, rocm.
      when: immich_machine_learning_hardware_acceleration not in ['armnn', 'cuda', 'cpu', 'openvino', 'openvino-wsl', 'rknn', 'rocm']
